# Generated by Django 3.2 on 2023-04-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredientsrecipe_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='tagsrecipe',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='IngredientsRecipe',
        ),
        migrations.DeleteModel(
            name='TagsRecipe',
        ),
    ]
