# Generated by Django 3.2 on 2023-04-28 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20230426_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_carts',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='shopping_carts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shopping_carts',
            name='name',
        ),
        migrations.AddField(
            model_name='shopping_carts',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts_recipe', to='recipes.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping_carts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts_user', to='users.user'),
            preserve_default=False,
        ),
    ]
